targets:
  $default:
    builders:
      laralite|laralite:
        enabled: true

builders:
  laralite:
    import: "package:laralite/builder.dart"
    builder_factories: ["laraliteBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
